[
  // Finance
  {
    "title": "Rich Dad Poor Dad",
    "author": "Robert Kiyosaki, Sharon Lechter",
    "category": "Finance",
    "description": "This personal finance classic contrasts the financial philosophies of two father figures: the 'poor dad,' a highly educated but financially struggling professor, and the 'rich dad,' a savvy entrepreneur. Through practical lessons, the authors emphasize financial literacy, investing, and building passive income streams. A global bestseller, it challenges conventional views on money and wealth-building.",
    "isbn": "9781612680194",
    "publisher": "Plata Publishing",
    "publishedYear": 1997,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781612680194-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Intelligent Investor",
    "author": "Benjamin Graham",
    "category": "Finance",
    "description": "Widely regarded as the definitive guide to value investing, this book outlines Benjamin Graham’s philosophy of buying undervalued stocks with strong fundamentals. Updated with commentary by Jason Zweig, it offers timeless strategies for managing risk and achieving long-term financial success, influencing investors like Warren Buffett.",
    "isbn": "9780060555665",
    "publisher": "Harper Business",
    "publishedYear": 1949,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780060555665-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Your Money or Your Life",
    "author": "Vicki Robin, Joe Dominguez",
    "category": "Finance",
    "description": "This transformative book offers a nine-step program to rethink your relationship with money, emphasizing financial independence through mindful spending and saving. With practical tools and inspiring stories, it guides readers toward financial freedom and a more fulfilling life.",
    "isbn": "9780143115762",
    "publisher": "Penguin Books",
    "publishedYear": 1992,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780143115762-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "A Random Walk Down Wall Street",
    "author": "Burton G. Malkiel",
    "category": "Finance",
    "description": "Burton Malkiel’s classic argues that markets are largely efficient, making it difficult to outperform them consistently. Advocating for index funds and diversification, this book provides accessible insights into investing strategies, debunking get-rich-quick schemes with data-driven analysis.",
    "isbn": "9780393358384",
    "publisher": "W.W. Norton & Company",
    "publishedYear": 1973,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780393358384-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Millionaire Next Door",
    "author": "Thomas J. Stanley, William D. Danko",
    "category": "Finance",
    "description": "Based on extensive research, this book reveals the habits of America’s wealthy, showing that many millionaires live frugally and prioritize saving over spending. It offers practical lessons on building wealth through discipline and smart financial choices.",
    "isbn": "9781589795471",
    "publisher": "Taylor Trade Publishing",
    "publishedYear": 1996,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781589795471-M.jpg",
    "availableCopies": 1,
    "totalCopies": 3
  },
  {
    "title": "Financial Freedom",
    "author": "Grant Sabatier",
    "category": "Finance",
    "description": "Grant Sabatier shares his journey from broke to financially independent in five years, offering actionable advice on saving, investing, and side hustles. This modern guide emphasizes practical steps to achieve financial freedom in today’s economy.",
    "isbn": "9780525534587",
    "publisher": "Avery",
    "publishedYear": 2019,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780525534587-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The Total Money Makeover",
    "author": "Dave Ramsey",
    "category": "Finance",
    "description": "Dave Ramsey’s step-by-step plan for financial fitness focuses on eliminating debt, building an emergency fund, and investing for the future. With a no-nonsense approach, this book has helped millions achieve financial stability through practical budgeting techniques.",
    "isbn": "9781595555274",
    "publisher": "Thomas Nelson",
    "publishedYear": 2003,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781595555274-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Think and Grow Rich",
    "author": "Napoleon Hill",
    "category": "Finance",
    "description": "A timeless self-help classic, this book explores the psychology of success and wealth-building through principles like desire, faith, and persistence. Based on interviews with successful individuals, it offers a mindset-driven approach to financial achievement.",
    "isbn": "9781585424337",
    "publisher": "TarcherPerigee",
    "publishedYear": 1937,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781585424337-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "The Little Book of Common Sense Investing",
    "author": "John C. Bogle",
    "category": "Finance",
    "description": "John Bogle, founder of Vanguard, advocates for low-cost index fund investing as the most reliable path to wealth. This concise book explains why passive investing outperforms most active strategies, making it a must-read for beginner investors.",
    "isbn": "9781119404507",
    "publisher": "Wiley",
    "publishedYear": 2007,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781119404507-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Principles: Life and Work",
    "author": "Ray Dalio",
    "category": "Finance",
    "description": "Ray Dalio, founder of Bridgewater Associates, shares his principles for success in life and finance. Combining personal memoir with practical advice, this book offers insights into decision-making, risk management, and building a successful career.",
    "isbn": "9781501124020",
    "publisher": "Simon & Schuster",
    "publishedYear": 2017,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781501124020-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Richest Man in Babylon",
    "author": "George S. Clason",
    "category": "Finance",
    "description": "Through parables set in ancient Babylon, this classic teaches timeless financial lessons like saving a portion of your income and avoiding debt. Its engaging storytelling makes complex financial concepts accessible to all readers.",
    "isbn": "9780451205360",
    "publisher": "Signet",
    "publishedYear": 1926,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780451205360-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "I Will Teach You to Be Rich",
    "author": "Ramit Sethi",
    "category": "Finance",
    "description": "Ramit Sethi’s modern guide to personal finance offers a six-week program to manage money effectively, from budgeting to investing. With a humorous and practical approach, it’s tailored for young adults seeking financial independence.",
    "isbn": "9781523505746",
    "publisher": "Workman Publishing",
    "publishedYear": 2009,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781523505746-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Wealth of Nations",
    "author": "Adam Smith",
    "category": "Finance",
    "description": "Adam Smith’s foundational work in economics explores the principles of free markets, division of labor, and wealth creation. A cornerstone of economic thought, it remains relevant for understanding capitalism and financial systems.",
    "isbn": "9780140432084",
    "publisher": "Penguin Classics",
    "publishedYear": 1776,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780140432084-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "The Money Book for the Young, Fabulous & Broke",
    "author": "Suze Orman",
    "category": "Finance",
    "description": "Suze Orman offers practical financial advice for young adults, covering credit, debt, and investing. With a focus on real-world challenges, this book empowers readers to take control of their financial future.",
    "isbn": "9781594482243",
    "publisher": "Riverhead Books",
    "publishedYear": 2005,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781594482243-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The Behavior Gap",
    "author": "Carl Richards",
    "category": "Finance",
    "description": "Carl Richards uses simple sketches and stories to illustrate how emotional decisions lead to financial mistakes. This book teaches readers to align their financial choices with their goals, avoiding common behavioral pitfalls.",
    "isbn": "9781591844648",
    "publisher": "Portfolio",
    "publishedYear": 2012,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781591844648-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Psychology of Money",
    "author": "Morgan Housel",
    "category": "Finance",
    "description": "Morgan Housel explores how behavior, not just knowledge, drives financial success. Through engaging stories, this book highlights timeless lessons on wealth, greed, and happiness, making it a modern finance classic.",
    "isbn": "9780857197689",
    "publisher": "Harriman House",
    "publishedYear": 2020,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780857197689-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Simple Path to Wealth",
    "author": "JL Collins",
    "category": "Finance",
    "description": "Originally a series of letters to his daughter, JL Collins’ book simplifies investing with a focus on index funds and financial independence. Its straightforward advice makes it a go-to for beginners and seasoned investors alike.",
    "isbn": "9781533667922",
    "publisher": "CreateSpace",
    "publishedYear": 2016,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781533667922-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Bajet Niti ra Abhyas",
    "author": "Dr. Madan Kumar Dahal",
    "category": "Finance",
    "description": "A comprehensive Nepali book on budgeting policies and practices, this work explores Nepal’s fiscal policies, economic planning, and financial management. Written by a prominent economist, it’s widely used in academic and policy circles for understanding Nepal’s economic framework.",
    "isbn": "9789937296731",
    "publisher": "Ekta Books",
    "publishedYear": 2015,
    "coverImage": "https://www.ektabooks.com/images/book/9789937296731.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Nepalma Arthik Sudhar",
    "author": "Dr. Pushpa Raj Rajkarnikar",
    "category": "Finance",
    "description": "This Nepali book delves into economic reforms in Nepal, analyzing monetary policies, banking systems, and liberalization efforts. It’s a key resource for students and policymakers studying Nepal’s transition to a market-driven economy.",
    "isbn": "9789937296748",
    "publisher": "Ratna Pustak Bhandar",
    "publishedYear": 2010,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296748.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Arthashastra ko Parichaya",
    "author": "Dr. Bishwambher Pyakuryal",
    "category": "Finance",
    "description": "An introductory Nepali text on economics, this book covers fundamental concepts like supply, demand, and fiscal policy with a focus on Nepal’s economy. Its clear explanations make it a popular choice for students and educators.",
    "isbn": "9789937296755",
    "publisher": "Buddha Publications",
    "publishedYear": 2018,
    "coverImage": "https://www.buddha publications.com/images/book/9789937296755.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Nepalma Banking ra Bima",
    "author": "Dr. Govinda Nepal",
    "category": "Finance",
    "description": "This Nepali book examines Nepal’s banking and insurance sectors, detailing their evolution, challenges, and regulatory frameworks. It’s a vital resource for understanding financial institutions in Nepal’s context.",
    "isbn": "9789937296762",
    "publisher": "Nova Publication",
    "publishedYear": 2017,
    "coverImage": "https://www.novapublication.com.np/images/book/9789937296762.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Arthik Bikash ko Aadhar",
    "author": "Dr. Ram Prasad Gyanwaly",
    "category": "Finance",
    "description": "Focusing on the foundations of economic development, this Nepali book explores Nepal’s economic policies, poverty reduction strategies, and growth challenges. It’s widely used in academic settings for its in-depth analysis.",
    "isbn": "9789937296779",
    "publisher": "Heritage Publishers",
    "publishedYear": 2016,
    "coverImage": "https://www.heritagebooks.com.np/images/book/9789937296779.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Nepalma Lagani ra Bikash",
    "author": "Dr. Keshav Dev Bhattarai",
    "category": "Finance",
    "description": "This Nepali book analyzes investment opportunities and development strategies in Nepal, covering foreign direct investment and economic growth. It’s a key text for understanding Nepal’s financial landscape.",
    "isbn": "9789937296786",
    "publisher": "Books Mandala",
    "publishedYear": 2019,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296786.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  // Business
  {
    "title": "Good to Great",
    "author": "Jim Collins",
    "category": "Business",
    "description": "Jim Collins’ seminal work examines why some companies transition from good to great, identifying key principles like disciplined people, thought, and action. Based on extensive research, it’s a must-read for leaders seeking sustainable success.",
    "isbn": "9780066620992",
    "publisher": "HarperBusiness",
    "publishedYear": 2001,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780066620992-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Lean Startup",
    "author": "Eric Ries",
    "category": "Business",
    "description": "Eric Ries introduces the Lean Startup methodology, emphasizing rapid prototyping, validated learning, and iterative product development. This book has revolutionized entrepreneurship, guiding startups to build sustainable businesses in uncertain markets.",
    "isbn": "9780307887894",
    "publisher": "Crown Business",
    "publishedYear": 2011,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780307887894-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Zero to One",
    "author": "Peter Thiel, Blake Masters",
    "category": "Business",
    "description": "Peter Thiel argues that true innovation comes from creating something entirely new, not copying what exists. This book offers insights into building monopolies, fostering creativity, and navigating competitive markets, drawing from Thiel’s experience as a PayPal co-founder.",
    "isbn": "9780804139298",
    "publisher": "Crown Business",
    "publishedYear": 2014,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780804139298-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The E-Myth Revisited",
    "author": "Michael E. Gerber",
    "category": "Business",
    "description": "Michael Gerber dispels myths about entrepreneurship, showing why small businesses fail and how to build systems for success. This book is a practical guide for entrepreneurs seeking to work on their business, not just in it.",
    "isbn": "9780887307287",
    "publisher": "HarperBusiness",
    "publishedYear": 1995,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780887307287-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Start with Why",
    "author": "Simon Sinek",
    "category": "Business",
    "description": "Simon Sinek’s influential book explores how great leaders inspire action by starting with a clear ‘why.’ Using examples like Apple and Martin Luther King Jr., it shows how purpose-driven leadership drives success.",
    "isbn": "9781591846444",
    "publisher": "Portfolio",
    "publishedYear": 2009,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781591846444-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Innovator’s Dilemma",
    "author": "Clayton M. Christensen",
    "category": "Business",
    "description": "Clayton Christensen explains why successful companies fail when faced with disruptive innovations. This book introduces the concept of disruptive technology, offering critical insights for businesses navigating change.",
    "isbn": "9781633691780",
    "publisher": "Harvard Business Review Press",
    "publishedYear": 1997,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781633691780-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Atomic Habits",
    "author": "James Clear",
    "category": "Business",
    "description": "James Clear’s bestselling book explores how small changes in habits can lead to remarkable results. With practical strategies for building good habits and breaking bad ones, it’s a must-read for personal and professional growth.",
    "isbn": "9780735211292",
    "publisher": "Avery",
    "publishedYear": 2018,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780735211292-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "The 7 Habits of Highly Effective People",
    "author": "Stephen R. Covey",
    "category": "Business",
    "description": "Stephen Covey’s classic outlines seven habits for personal and professional effectiveness, from being proactive to seeking win-win solutions. Its timeless principles have guided millions in leadership and self-improvement.",
    "isbn": "9781982137274",
    "publisher": "Simon & Schuster",
    "publishedYear": 1989,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781982137274-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Leaders Eat Last",
    "author": "Simon Sinek",
    "category": "Business",
    "description": "Simon Sinek explores why great leaders prioritize their team’s well-being, creating trust and collaboration. Drawing from military and corporate examples, this book offers insights into building strong, loyal organizations.",
    "isbn": "9781591848011",
    "publisher": "Portfolio",
    "publishedYear": 2014,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781591848011-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "category": "Business",
    "description": "Nobel laureate Daniel Kahneman explores the two systems of thinking—fast and slow—that shape our decisions. This groundbreaking book offers insights into cognitive biases, impacting business and personal decision-making.",
    "isbn": "9780374533557",
    "publisher": "Farrar, Straus and Giroux",
    "publishedYear": 2011,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780374533557-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Hard Thing About Hard Things",
    "author": "Ben Horowitz",
    "category": "Business",
    "description": "Ben Horowitz shares raw, honest advice on running a startup, tackling the tough challenges leaders face. Drawing from his experience as a tech entrepreneur, this book is a practical guide for navigating business complexities.",
    "isbn": "9780062273208",
    "publisher": "HarperBusiness",
    "publishedYear": 2014,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780062273208-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The 4-Hour Workweek",
    "author": "Timothy Ferriss",
    "category": "Business",
    "description": "Timothy Ferriss introduces the concept of lifestyle design, showing how to escape the 9–5 grind through automation and outsourcing. This influential book inspires entrepreneurs to prioritize efficiency and freedom.",
    "isbn": "9780307465351",
    "publisher": "Crown Publishing",
    "publishedYear": 2007,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780307465351-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "How to Win Friends and Influence People",
    "author": "Dale Carnegie",
    "category": "Business",
    "description": "Dale Carnegie’s timeless classic offers practical advice on building relationships, influencing others, and effective communication. A cornerstone of personal and business success, it remains relevant across generations.",
    "isbn": "9780671027032",
    "publisher": "Pocket Books",
    "publishedYear": 1936,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780671027032-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "The Power of Habit",
    "author": "Charles Duhigg",
    "category": "Business",
    "description": "Charles Duhigg explores the science of habits, showing how they shape individuals and organizations. With case studies from Starbucks to the NFL, this book provides strategies for leveraging habits in business and life.",
    "isbn": "9780812981605",
    "publisher": "Random House",
    "publishedYear": 2012,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780812981605-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Measure What Matters",
    "author": "John Doerr",
    "category": "Business",
    "description": "John Doerr introduces OKRs (Objectives and Key Results), a goal-setting system used by Google and other top companies. This book shows how to align teams and drive success through measurable outcomes.",
    "isbn": "9780525536222",
    "publisher": "Portfolio",
    "publishedYear": 2018,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780525536222-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Business Adventures",
    "author": "John Brooks",
    "category": "Business",
    "description": "A collection of New Yorker articles, this book offers timeless stories of business successes and failures, from Xerox to Ford. Praised by Bill Gates, it provides enduring lessons on corporate strategy and leadership.",
    "isbn": "9781497644892",
    "publisher": "Open Road Media",
    "publishedYear": 1969,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781497644892-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Wyakaran ra Uddyam",
    "author": "Dr. Madan Kumar Bhattarai",
    "category": "Business",
    "description": "This Nepali book explores entrepreneurship and business management principles tailored to Nepal’s economic context. It covers startup strategies, market analysis, and case studies of Nepali businesses, making it a key resource for local entrepreneurs.",
    "isbn": "9789937296793",
    "publisher": "Ekta Books",
    "publishedYear": 2016,
    "coverImage": "https://www.ektabooks.com/images/book/9789937296793.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Nepalma Byabasayik Niti",
    "author": "Dr. Govind Ram Agrawal",
    "category": "Business",
    "description": "Focusing on business policies in Nepal, this book analyzes regulatory frameworks, trade policies, and economic strategies. It’s a popular text for understanding Nepal’s business environment and its challenges.",
    "isbn": "9789937296809",
    "publisher": "Ratna Pustak Bhandar",
    "publishedYear": 2014,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296809.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Uddyamshilta ra Byawasthapan",
    "author": "Dr. Bihari Binod Pokharel",
    "category": "Business",
    "description": "A comprehensive Nepali guide to entrepreneurship and management, this book covers leadership, organizational behavior, and startup strategies with a focus on Nepal’s market dynamics. It’s widely used in business education.",
    "isbn": "9789937296816",
    "publisher": "Buddha Publications",
    "publishedYear": 2017,
    "coverImage": "https://www.buddha publications.com/images/book/9789937296816.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Nepalma Byapar ra Bazaar",
    "author": "Dr. Shyam Krishna Shrestha",
    "category": "Business",
    "description": "This Nepali book explores trade and market dynamics in Nepal, covering supply chains, consumer behavior, and market trends. It’s a key resource for understanding Nepal’s commercial landscape.",
    "isbn": "9789937296823",
    "publisher": "Nova Publication",
    "publishedYear": 2018,
    "coverImage": "https://www.novapublication.com.np/images/book/9789937296823.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Byabasayik Siddhanta",
    "author": "Dr. Rajan Bahadur Paudel",
    "category": "Business",
    "description": "This Nepali text introduces business principles, including management, marketing, and finance, with examples from Nepal’s economy. It’s a popular academic resource for business students in Nepal.",
    "isbn": "9789937296830",
    "publisher": "Heritage Publishers",
    "publishedYear": 2015,
    "coverImage": "https://www.heritagebooks.com.np/images/book/9789937296830.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  // Arts
  {
    "title": "The Story of Art",
    "author": "E.H. Gombrich",
    "category": "Arts",
    "description": "This classic art history book traces the evolution of art from prehistoric times to the modern era. Gombrich’s accessible narrative and rich illustrations make it a definitive guide for art enthusiasts and scholars.",
    "isbn": "9780714847030",
    "publisher": "Phaidon Press",
    "publishedYear": 1950,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780714847030-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Ways of Seeing",
    "author": "John Berger",
    "category": "Arts",
    "description": "Based on a BBC series, John Berger’s book challenges how we view art, exploring its cultural and social contexts. Its insights into visual culture, gender, and power remain influential in art criticism.",
    "isbn": "9780140135152",
    "publisher": "Penguin Books",
    "publishedYear": 1972,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780140135152-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Art & Fear",
    "author": "David Bayles, Ted Orland",
    "category": "Arts",
    "description": "This book explores the emotional and psychological challenges artists face, from self-doubt to creative blocks. Offering practical advice, it’s a beloved guide for artists seeking to sustain their creative practice.",
    "isbn": "9780961454739",
    "publisher": "Image Continuum Press",
    "publishedYear": 1993,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780961454739-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Artist’s Way",
    "author": "Julia Cameron",
    "category": "Arts",
    "description": "Julia Cameron’s 12-week program helps artists and non-artists unlock creativity through exercises like morning pages. A spiritual and practical guide, it’s a bestseller for fostering artistic expression.",
    "isbn": "9781585421466",
    "publisher": "TarcherPerigee",
    "publishedYear": 1992,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781585421466-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Steal Like an Artist",
    "author": "Austin Kleon",
    "category": "Arts",
    "description": "Austin Kleon’s concise guide encourages creatives to embrace influence, remix ideas, and find their unique voice. With practical tips and playful illustrations, it’s a modern classic for artists and innovators.",
    "isbn": "9780761169253",
    "publisher": "Workman Publishing",
    "publishedYear": 2012,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780761169253-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "Understanding Comics",
    "author": "Scott McCloud",
    "category": "Arts",
    "description": "Scott McCloud’s graphic novel explores the art and theory of comics, analyzing their visual language and cultural impact. A groundbreaking work, it’s essential for understanding sequential art.",
    "isbn": "9780060976255",
    "publisher": "William Morrow",
    "publishedYear": 1993,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780060976255-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Art Book",
    "author": "Phaidon Editors",
    "category": "Arts",
    "description": "This visually stunning book presents 500 artworks from different periods and cultures, each accompanied by concise commentary. It’s an accessible introduction to art history for readers of all levels.",
    "isbn": "9780714864679",
    "publisher": "Phaidon Press",
    "publishedYear": 1994,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780714864679-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Shock of the New",
    "author": "Robert Hughes",
    "category": "Arts",
    "description": "Robert Hughes chronicles the development of modern art, from Impressionism to Abstract Expressionism. With sharp analysis and vivid storytelling, it’s a definitive guide to 20th-century art movements.",
    "isbn": "9780070311275",
    "publisher": "McGraw-Hill",
    "publishedYear": 1980,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780070311275-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Art Through the Ages",
    "author": "Helen Gardner",
    "category": "Arts",
    "description": "A comprehensive art history textbook, this book covers global art from prehistory to the present. With detailed analyses and rich illustrations, it’s a staple for art students and enthusiasts.",
    "isbn": "9780155083158",
    "publisher": "Harcourt Brace",
    "publishedYear": 1926,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780155083158-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "The Lives of the Artists",
    "author": "Giorgio Vasari",
    "category": "Arts",
    "description": "Written in the 16th century, Vasari’s biographies of Renaissance artists like Michelangelo and Leonardo da Vinci are a foundational text in art history. It offers vivid portraits of creative geniuses.",
    "isbn": "9780192834102",
    "publisher": "Oxford University Press",
    "publishedYear": 1550,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780192834102-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Creative Act",
    "author": "Rick Rubin",
    "category": "Arts",
    "description": "Legendary music producer Rick Rubin shares insights on creativity, drawing from his work with artists like Johnny Cash and Adele. This book offers a philosophical guide to unlocking artistic potential.",
    "isbn": "9780593652886",
    "publisher": "Penguin Press",
    "publishedYear": 2023,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780593652886-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Show Your Work!",
    "author": "Austin Kleon",
    "category": "Arts",
    "description": "A follow-up to Steal Like an Artist, this book encourages creatives to share their process and build an audience. With practical advice and humor, it’s a guide for artists navigating the digital age.",
    "isbn": "9780761178972",
    "publisher": "Workman Publishing",
    "publishedYear": 2014,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780761178972-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The War of Art",
    "author": "Steven Pressfield",
    "category": "Arts",
    "description": "Steven Pressfield explores the concept of creative resistance, offering strategies to overcome fear and procrastination. This motivational book is a favorite among artists and writers seeking discipline.",
    "isbn": "9781936891023",
    "publisher": "Black Irish Entertainment",
    "publishedYear": 2002,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781936891023-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Women, Art, and Society",
    "author": "Whitney Chadwick",
    "category": "Arts",
    "description": "This book explores the contributions of women artists across history, addressing gender biases in the art world. With rich illustrations and analysis, it’s a vital text for feminist art studies.",
    "isbn": "9780500204054",
    "publisher": "Thames & Hudson",
    "publishedYear": 1990,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780500204054-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The Art Spirit",
    "author": "Robert Henri",
    "category": "Arts",
    "description": "Robert Henri’s collection of essays and lectures inspires artists to find their unique voice and embrace authenticity. A classic for art students, it emphasizes passion and individuality in creative work.",
    "isbn": "9780465002634",
    "publisher": "Basic Books",
    "publishedYear": 1923,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780465002634-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Nepali Kala ra Sanskriti",
    "author": "Satyamohan Joshi",
    "category": "Arts",
    "description": "This iconic Nepali book explores Nepal’s rich artistic and cultural heritage, covering traditional art, architecture, and festivals. Written by a renowned cultural scholar, it’s a definitive resource on Nepali arts.",
    "isbn": "9789937296847",
    "publisher": "Ratna Pustak Bhandar",
    "publishedYear": 2005,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296847.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Nepali Loka Kala",
    "author": "Lain Singh Bangdel",
    "category": "Arts",
    "description": "This Nepali book delves into Nepal’s folk art, including paintings, sculptures, and crafts. Bangdel, a pioneer of modern Nepali art, provides a detailed analysis of traditional artistic practices.",
    "isbn": "9789937296854",
    "publisher": "Ekta Books",
    "publishedYear": 1999,
    "coverImage": "https://www.ektabooks.com/images/book/9789937296854.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Himalayan Kala",
    "author": "Madan Chitrakar",
    "category": "Arts",
    "description": "This Nepali book explores the art of the Himalayan region, focusing on Nepal’s thangka paintings and religious iconography. It’s a beautifully illustrated guide to Nepal’s spiritual art traditions.",
    "isbn": "9789937296861",
    "publisher": "Buddha Publications",
    "publishedYear": 2010,
    "coverImage": "https://www.buddha publications.com/images/book/9789937296861.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Nepali Chitrakala",
    "author": "Yamuna Karki",
    "category": "Arts",
    "description": "A comprehensive study of Nepali painting, this book covers traditional and modern art forms, including Paubha and contemporary styles. It’s a key text for understanding Nepal’s visual arts evolution.",
    "isbn": "9789937296878",
    "publisher": "Nova Publication",
    "publishedYear": 2012,
    "coverImage": "https://www.novapublication.com.np/images/book/9789937296878.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Nepali Sanskritik Kala",
    "author": "Jagadish Chandra Regmi",
    "category": "Arts",
    "description": "This Nepali book examines the cultural arts of Nepal, including music, dance, and visual arts, with a focus on their historical and social significance. It’s widely respected in Nepali art studies.",
    "isbn": "9789937296885",
    "publisher": "Heritage Publishers",
    "publishedYear": 2008,
    "coverImage": "https://www.heritagebooks.com.np/images/book/9789937296885.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  // Technology
  {
    "title": "The Innovators",
    "author": "Walter Isaacson",
    "category": "Technology",
    "description": "Walter Isaacson chronicles the history of the digital revolution, profiling innovators like Ada Lovelace, Alan Turing, and Steve Jobs. This book highlights the collaborative nature of technological breakthroughs.",
    "isbn": "9781476708690",
    "publisher": "Simon & Schuster",
    "publishedYear": 2014,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781476708690-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Code Book",
    "author": "Simon Singh",
    "category": "Technology",
    "description": "Simon Singh explores the history of cryptography, from ancient ciphers to modern encryption. With engaging storytelling, it explains how codebreaking has shaped technology, wars, and privacy.",
    "isbn": "9780385495325",
    "publisher": "Anchor Books",
    "publishedYear": 1999,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780385495325-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Hacking: The Art of Exploitation",
    "author": "Jon Erickson",
    "category": "Technology",
    "description": "This technical guide introduces the principles of hacking, covering programming, networking, and security vulnerabilities. With hands-on examples, it’s a key resource for cybersecurity enthusiasts.",
    "isbn": "9781593271442",
    "publisher": "No Starch Press",
    "publishedYear": 2008,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781593271442-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Mythical Man-Month",
    "author": "Frederick P. Brooks Jr.",
    "category": "Technology",
    "description": "A classic in software engineering, this book explores the challenges of managing large software projects. Brooks’ insights, like the law that adding manpower delays projects, remain relevant today.",
    "isbn": "9780201835953",
    "publisher": "Addison-Wesley",
    "publishedYear": 1975,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780201835953-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Clean Code",
    "author": "Robert C. Martin",
    "category": "Technology",
    "description": "Robert C. Martin offers principles for writing clean, maintainable code, emphasizing readability and simplicity. A must-read for programmers, it’s filled with practical examples and best practices.",
    "isbn": "9780132350884",
    "publisher": "Prentice Hall",
    "publishedYear": 2008,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780132350884-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Pragmatic Programmer",
    "author": "Andrew Hunt, David Thomas",
    "category": "Technology",
    "description": "This influential book offers practical advice for software developers, covering topics like code organization, testing, and career growth. Its timeless tips are essential for programmers at all levels.",
    "isbn": "9780135957059",
    "publisher": "Addison-Wesley",
    "publishedYear": 1999,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780135957059-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The Art of Computer Programming",
    "author": "Donald E. Knuth",
    "category": "Technology",
    "description": "Donald Knuth’s multi-volume work is a cornerstone of computer science, covering algorithms and data structures in depth. A rigorous yet accessible resource, it’s revered by programmers and academics.",
    "isbn": "9780201896831",
    "publisher": "Addison-Wesley",
    "publishedYear": 1968,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780201896831-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "You Don’t Know JS",
    "author": "Kyle Simpson",
    "category": "Technology",
    "description": "This popular series dives deep into JavaScript, covering its quirks and advanced concepts. Written in an engaging style, it’s a go-to resource for web developers mastering the language.",
    "isbn": "9781491924464",
    "publisher": "O'Reilly Media",
    "publishedYear": 2014,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781491924464-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Phoenix Project",
    "author": "Gene Kim, Kevin Behr, George Spafford",
    "category": "Technology",
    "description": "A novel about IT and DevOps, this book follows an IT manager navigating a failing project. Through storytelling, it introduces DevOps principles, making it a favorite among tech professionals.",
    "isbn": "9781942788294",
    "publisher": "IT Revolution Press",
    "publishedYear": 2013,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781942788294-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Superintelligence",
    "author": "Nick Bostrom",
    "category": "Technology",
    "description": "Nick Bostrom explores the implications of artificial intelligence surpassing human intelligence. This thought-provoking book examines AI’s risks and opportunities, shaping discussions on technology’s future.",
    "isbn": "9780199678112",
    "publisher": "Oxford University Press",
    "publishedYear": 2014,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780199678112-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Cathedral and the Bazaar",
    "author": "Eric S. Raymond",
    "category": "Technology",
    "description": "This influential essay collection explores open-source software development, contrasting collaborative ‘bazaar’ models with traditional ‘cathedral’ approaches. A key text for understanding open-source culture.",
    "isbn": "9780596001087",
    "publisher": "O'Reilly Media",
    "publishedYear": 1999,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780596001087-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Designing Data-Intensive Applications",
    "author": "Martin Kleppmann",
    "category": "Technology",
    "description": "This technical book explores the architecture of scalable, reliable data systems, covering databases, distributed systems, and big data. It’s a critical resource for software engineers working on modern applications.",
    "isbn": "9781449373320",
    "publisher": "O'Reilly Media",
    "publishedYear": 2017,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781449373320-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Life 3.0",
    "author": "Max Tegmark",
    "category": "Technology",
    "description": "Max Tegmark examines the future of artificial intelligence, exploring its impact on society, work, and humanity. This book blends science and philosophy to address AI’s transformative potential.",
    "isbn": "9781101970317",
    "publisher": "Vintage",
    "publishedYear": 2017,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781101970317-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Coders at Work",
    "author": "Peter Seibel",
    "category": "Technology",
    "description": "This book features interviews with legendary programmers like Donald Knuth and Jamie Zawinski, offering insights into their craft and problem-solving approaches. It’s a fascinating read for tech enthusiasts.",
    "isbn": "9781430219484",
    "publisher": "Apress",
    "publishedYear": 2009,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781430219484-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Soul of a New Machine",
    "author": "Tracy Kidder",
    "category": "Technology",
    "description": "Tracy Kidder’s Pulitzer Prize-winning book chronicles the development of a new computer at Data General in the 1970s. A gripping narrative, it captures the intensity of innovation in tech.",
    "isbn": "9780316491976",
    "publisher": "Back Bay Books",
    "publishedYear": 1981,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780316491976-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Nepalma Suchana Praudyogiki",
    "author": "Dr. Subarna Shakya",
    "category": "Technology",
    "description": "This Nepali book explores the development of information technology in Nepal, covering software, networking, and digital policies. It’s a key resource for understanding Nepal’s tech landscape.",
    "isbn": "9789937296892",
    "publisher": "Ekta Books",
    "publishedYear": 2018,
    "coverImage": "https://www.ektabooks.com/images/book/9789937296892.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Nepali Software Bikas",
    "author": "Dr. Rabin Sharma",
    "category": "Technology",
    "description": "Focusing on software development in Nepal, this book covers programming trends, local startups, and challenges in the tech industry. It’s popular among Nepali tech students and professionals.",
    "isbn": "9789937296908",
    "publisher": "Ratna Pustak Bhandar",
    "publishedYear": 2016,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296908.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Suchana ra Sanchar Praudyogiki",
    "author": "Dr. Manish Pokharel",
    "category": "Technology",
    "description": "This Nepali book examines information and communication technologies in Nepal, including telecom and internet infrastructure. It’s widely used in academic settings for its comprehensive coverage.",
    "isbn": "9789937296915",
    "publisher": "Buddha Publications",
    "publishedYear": 2019,
    "coverImage": "https://www.buddha publications.com/images/book/9789937296915.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Nepalma Digital Sansar",
    "author": "Dr. Bhoj Raj Ghimire",
    "category": "Technology",
    "description": "Exploring Nepal’s digital transformation, this book covers e-commerce, digital governance, and cybersecurity. It’s a key text for understanding Nepal’s growing tech ecosystem.",
    "isbn": "9789937296922",
    "publisher": "Nova Publication",
    "publishedYear": 2020,
    "coverImage": "https://www.novapublication.com.np/images/book/9789937296922.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Computer Bigyan ra Praudyogiki",
    "author": "Dr. Deepak Adhikari",
    "category": "Technology",
    "description": "This Nepali book introduces computer science and technology, covering programming, algorithms, and hardware with a focus on Nepal’s context. It’s a popular resource for tech students.",
    "isbn": "9789937296939",
    "publisher": "Heritage Publishers",
    "publishedYear": 2017,
    "coverImage": "https://www.heritagebooks.com.np/images/book/9789937296939.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  // Literature
  {
    "title": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "category": "Literature",
    "description": "Set in 1930s Alabama, this Pulitzer Prize-winning novel follows Scout Finch as her father, Atticus, defends a Black man wrongly accused of a crime. A powerful exploration of racism, morality, and empathy, it’s a cornerstone of American literature.",
    "isbn": "9780446310789",
    "publisher": "Grand Central Publishing",
    "publishedYear": 1960,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780446310789-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "category": "Literature",
    "description": "Jane Austen’s classic follows Elizabeth Bennet as she navigates love, societal expectations, and family pressures in 19th-century England. With sharp wit and rich characters, it’s a timeless romance and social satire.",
    "isbn": "9780141439518",
    "publisher": "Penguin Classics",
    "publishedYear": 1813,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780141439518-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "1984",
    "author": "George Orwell",
    "category": "Literature",
    "description": "George Orwell’s dystopian novel depicts a totalitarian society where surveillance and propaganda crush individuality. Winston Smith’s rebellion against Big Brother explores themes of freedom, truth, and oppression.",
    "isbn": "9780451524935",
    "publisher": "Signet Classics",
    "publishedYear": 1949,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780451524935-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "category": "Literature",
    "description": "Set in the Jazz Age, this novel follows Jay Gatsby’s obsessive love for Daisy Buchanan, exploring the American Dream and disillusionment. Fitzgerald’s lyrical prose captures the glamour and tragedy of the 1920s.",
    "isbn": "9780743273565",
    "publisher": "Scribner",
    "publishedYear": 1925,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780743273565-M.jpg",
    "availableCopies": 1,
    "totalCopies": 3
  },
  {
    "title": "Jane Eyre",
    "author": "Charlotte Brontë",
    "category": "Literature",
    "description": "This gothic romance follows Jane Eyre’s journey from a harsh childhood to her complex love for Mr. Rochester. Brontë’s novel explores independence, morality, and love, making it a literary classic.",
    "isbn": "9780141441146",
    "publisher": "Penguin Classics",
    "publishedYear": 1847,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780141441146-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "category": "Literature",
    "description": "Narrated by the disillusioned teenager Holden Caulfield, this novel captures the angst of youth in post-war America. Salinger’s raw, introspective narrative explores identity, alienation, and rebellion.",
    "isbn": "9780316769488",
    "publisher": "Little, Brown and Company",
    "publishedYear": 1951,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780316769488-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Moby-Dick",
    "author": "Herman Melville",
    "category": "Literature",
    "description": "This epic novel follows Ishmael and Captain Ahab’s obsessive quest for the white whale, Moby Dick. Melville’s rich prose explores fate, nature, and human ambition in a monumental work of American literature.",
    "isbn": "9780142437247",
    "publisher": "Penguin Classics",
    "publishedYear": 1851,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780142437247-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Wuthering Heights",
    "author": "Emily Brontë",
    "category": "Literature",
    "description": "This haunting novel explores the passionate, destructive love between Heathcliff and Catherine Earnshaw on the Yorkshire moors. Emily Brontë’s gothic masterpiece delves into revenge, class, and human emotion.",
    "isbn": "9780141439556",
    "publisher": "Penguin Classics",
    "publishedYear": 1847,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780141439556-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Hobbit",
    "author": "J.R.R. Tolkien",
    "category": "Literature",
    "description": "This fantasy classic follows Bilbo Baggins’ adventure with dwarves and Gandalf to reclaim a stolen treasure. Tolkien’s enchanting tale of courage and discovery is a beloved precursor to The Lord of the Rings.",
    "isbn": "9780547928227",
    "publisher": "Houghton Mifflin Harcourt",
    "publishedYear": 1937,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780547928227-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "category": "Literature",
    "description": "Aldous Huxley’s dystopian novel depicts a future where genetic engineering and drugs ensure conformity. Through Bernard Marx and John the Savage, it critiques technology, freedom, and societal control.",
    "isbn": "9780060850524",
    "publisher": "Harper Perennial",
    "publishedYear": 1932,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780060850524-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Lord of the Flies",
    "author": "William Golding",
    "category": "Literature",
    "description": "When schoolboys are stranded on an island, their attempts at order descend into savagery. Golding’s allegory explores human nature, power, and the fragility of civilization in a gripping narrative.",
    "isbn": "9780399501487",
    "publisher": "Perigee Books",
    "publishedYear": 1954,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780399501487-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Grapes of Wrath",
    "author": "John Steinbeck",
    "category": "Literature",
    "description": "This Pulitzer Prize-winning novel follows the Joad family’s migration during the Great Depression, exploring poverty, injustice, and resilience. Steinbeck’s vivid prose captures the American experience.",
    "isbn": "9780143039433",
    "publisher": "Penguin Classics",
    "publishedYear": 1939,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780143039433-M.jpg",
    "availableCopies": 1,
    "totalCopies": 3
  },
  {
    "title": "Catch-22",
    "author": "Joseph Heller",
    "category": "Literature",
    "description": "Joseph Heller’s satirical novel follows Captain Yossarian during World War II, exposing the absurdity of war and bureaucracy. Its dark humor and paradoxical Catch-22 situations make it a literary classic.",
    "isbn": "9781451626650",
    "publisher": "Simon & Schuster",
    "publishedYear": 1961,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781451626650-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Animal Farm",
    "author": "George Orwell",
    "category": "Literature",
    "description": "This allegorical novella depicts farm animals overthrowing their owner, only to face new tyranny. Orwell’s satire critiques totalitarianism and power, drawing parallels to the Russian Revolution.",
    "isbn": "9780451526342",
    "publisher": "Signet Classics",
    "publishedYear": 1945,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780451526342-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Beloved",
    "author": "Toni Morrison",
    "category": "Literature",
    "description": "Toni Morrison’s Pulitzer Prize-winning novel follows Sethe, a former slave haunted by her past and her daughter’s ghost. Its lyrical prose explores memory, trauma, and the legacy of slavery.",
    "isbn": "9781400033416",
    "publisher": "Vintage",
    "publishedYear": 1987,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781400033416-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Muna Madan",
    "author": "Laxmi Prasad Devkota",
    "category": "Literature",
    "description": "A cornerstone of Nepali literature, this epic poem narrates the tragic love story of Muna and Madan, exploring themes of love, sacrifice, and societal constraints. Devkota’s lyrical style makes it a timeless classic.",
    "isbn": "9789937296946",
    "publisher": "Sajha Prakashan",
    "publishedYear": 1936,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296946.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Seto Bagh",
    "author": "Diamond Shumsher Rana",
    "category": "Literature",
    "description": "This historical novel depicts the fall of Nepal’s Rana dynasty through the life of Jagat Jung Rana. Blending fact and fiction, it’s a gripping tale of power, betrayal, and tragedy in Nepali literature.",
    "isbn": "9789937296953",
    "publisher": "Ratna Pustak Bhandar",
    "publishedYear": 1973,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296953.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Palpasa Café",
    "author": "Narayan Wagle",
    "category": "Literature",
    "description": "A modern Nepali novel, Palpasa Café tells the story of an artist and a woman during Nepal’s Maoist insurgency. Blending romance, war, and social commentary, it’s a bestseller in Nepali literature.",
    "isbn": "9789937296960",
    "publisher": "Nepalaya",
    "publishedYear": 2005,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296960.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Shirishko Phool",
    "author": "Parijat",
    "category": "Literature",
    "description": "This existential Nepali novel follows a war veteran grappling with life’s meaning and his love for a woman named Shirish. Parijat’s lyrical prose makes it a landmark in Nepali literature.",
    "isbn": "9789937296977",
    "publisher": "Sajha Prakashan",
    "publishedYear": 1965,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296977.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Karnali Blues",
    "author": "Buddhisagar",
    "category": "Literature",
    "description": "This contemporary Nepali novel follows a son’s relationship with his father in rural Nepal, blending humor, nostalgia, and emotional depth. It’s a modern classic celebrated for its vivid storytelling.",
    "isbn": "9789937296984",
    "publisher": "FinePrint",
    "publishedYear": 2010,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296984.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Jhola",
    "author": "Krishna Dharabasi",
    "category": "Literature",
    "description": "Based on a true story, this Nepali novel explores the tragic practice of Sati in 19th-century Nepal. Its poignant narrative and social critique make it a powerful work in Nepali literature.",
    "isbn": "9789937296991",
    "publisher": "Book Hill",
    "publishedYear": 2008,
    "coverImage": "https://www.booksmandala.com/images/book/9789937296991.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
//   History
  {
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "category": "History",
    "description": "Yuval Noah Harari traces humanity’s history from the Stone Age to the modern era, exploring cognitive, agricultural, and scientific revolutions. This engaging narrative rethinks our species’ past and future.",
    "isbn": "9780062316097",
    "publisher": "Harper",
    "publishedYear": 2011,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780062316097-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "category": "History",
    "description": "Yuval Noah Harari’s sweeping narrative traces the history of Homo sapiens from the Stone Age to the modern era, exploring the cognitive, agricultural, and scientific revolutions that shaped our species. With accessible prose, it examines how culture, biology, and technology drove human progress, offering provocative insights into our past and future.",
    "isbn": "9780062316097",
    "publisher": "Harper",
    "publishedYear": 2011,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780062316097-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Guns, Germs, and Steel",
    "author": "Jared Diamond",
    "category": "History",
    "description": "This Pulitzer Prize-winning book explores why some societies developed advanced technologies and dominated others, attributing differences to geography, resources, and biology. Jared Diamond’s interdisciplinary approach spans anthropology, history, and ecology, offering a compelling framework for understanding global inequalities.",
    "isbn": "9780393317558",
    "publisher": "W.W. Norton & Company",
    "publishedYear": 1997,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780393317558-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "A People’s History of the United States",
    "author": "Howard Zinn",
    "category": "History",
    "description": "Howard Zinn’s groundbreaking work tells America’s history from the perspective of marginalized groups—workers, Native Americans, and slaves. Challenging traditional narratives, it highlights struggles for justice and equality, making it a vital text for understanding the untold stories of the U.S.",
    "isbn": "9780062397348",
    "publisher": "Harper Perennial",
    "publishedYear": 1980,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780062397348-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Guns of August",
    "author": "Barbara W. Tuchman",
    "category": "History",
    "description": "This Pulitzer Prize-winning book chronicles the first month of World War I, detailing the diplomatic failures and military strategies that led to catastrophe. Tuchman’s vivid narrative captures the human drama and strategic missteps of 1914, offering timeless lessons on conflict.",
    "isbn": "9780345476098",
    "publisher": "Presidio Press",
    "publishedYear": 1962,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780345476098-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Rise and Fall of the Third Reich",
    "author": "William L. Shirer",
    "category": "History",
    "description": "William Shirer’s definitive history of Nazi Germany chronicles Hitler’s rise, the Third Reich’s expansion, and its collapse. Based on firsthand accounts and extensive research, this monumental work offers a gripping, detailed look at one of history’s darkest periods.",
    "isbn": "9781451651683",
    "publisher": "Simon & Schuster",
    "publishedYear": 1960,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781451651683-M.jpg",
    "availableCopies": 1,
    "totalCopies": 3
  },
  {
    "title": "The Histories",
    "author": "Herodotus",
    "category": "History",
    "description": "Written in the 5th century BCE, Herodotus’ work is considered the founding text of history. Chronicling the Greco-Persian Wars and diverse cultures, its blend of storytelling and inquiry offers a fascinating glimpse into the ancient world.",
    "isbn": "9780140449082",
    "publisher": "Penguin Classics",
    "publishedYear": 440,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780140449082-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Team of Rivals",
    "author": "Doris Kearns Goodwin",
    "category": "History",
    "description": "This acclaimed biography explores Abraham Lincoln’s leadership during the Civil War, focusing on his cabinet of political rivals. Goodwin’s narrative reveals Lincoln’s genius in uniting diverse figures to preserve the Union, offering lessons in leadership and diplomacy.",
    "isbn": "9780743270755",
    "publisher": "Simon & Schuster",
    "publishedYear": 2005,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780743270755-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Decline and Fall of the Roman Empire",
    "author": "Edward Gibbon",
    "category": "History",
    "description": "Edward Gibbon’s monumental work traces the Roman Empire’s decline from its peak to its fall in 1453. With meticulous research and eloquent prose, it remains a cornerstone of historical writing, exploring power, culture, and collapse.",
    "isbn": "9780140437645",
    "publisher": "Penguin Classics",
    "publishedYear": 1776,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780140437645-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "The Immortal Life of Henrietta Lacks",
    "author": "Rebecca Skloot",
    "category": "History",
    "description": "This compelling narrative chronicles the life of Henrietta Lacks, whose cancer cells were taken without consent in 1951, revolutionizing medical research. Skloot explores the ethical, racial, and scientific implications, weaving a powerful story of history and humanity.",
    "isbn": "9781400052189",
    "publisher": "Crown Publishing",
    "publishedYear": 2010,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781400052189-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "A Short History of Nearly Everything",
    "author": "Bill Bryson",
    "category": "History",
    "description": "Bill Bryson’s engaging book traces the history of science, from the Big Bang to modern discoveries. With humor and clarity, it explores the scientists and events that shaped our understanding of the universe, making history accessible and entertaining.",
    "isbn": "9780767908184",
    "publisher": "Broadway Books",
    "publishedYear": 2003,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780767908184-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Silk Roads",
    "author": "Peter Frankopan",
    "category": "History",
    "description": "Peter Frankopan reorients world history around the Silk Roads, showing how this network shaped global trade, culture, and power. With rich storytelling, it challenges Eurocentric narratives and highlights Asia’s historical significance.",
    "isbn": "9781101912379",
    "publisher": "Vintage",
    "publishedYear": 2015,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781101912379-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "SPQR: A History of Ancient Rome",
    "author": "Mary Beard",
    "category": "History",
    "description": "Mary Beard’s engaging history of Rome explores its rise from a village to an empire. Blending scholarship with storytelling, it covers politics, culture, and daily life, offering a vivid portrait of ancient Rome.",
    "isbn": "9781631492228",
    "publisher": "Liveright",
    "publishedYear": 2015,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781631492228-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "The Diary of a Young Girl",
    "author": "Anne Frank",
    "category": "History",
    "description": "Anne Frank’s diary, written while hiding from the Nazis, offers a poignant, personal account of life during the Holocaust. Her reflections on hope, fear, and humanity make this a powerful historical document.",
    "isbn": "9780553577129",
    "publisher": "Bantam Books",
    "publishedYear": 1947,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780553577129-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "The Warmth of Other Suns",
    "author": "Isabel Wilkerson",
    "category": "History",
    "description": "Isabel Wilkerson chronicles the Great Migration of African Americans from the South to the North and West, weaving personal stories with historical analysis. This powerful narrative explores race, opportunity, and America’s history.",
    "isbn": "9780679763888",
    "publisher": "Vintage",
    "publishedYear": 2010,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780679763888-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Bury My Heart at Wounded Knee",
    "author": "Dee Brown",
    "category": "History",
    "description": "Dee Brown’s seminal work recounts the systematic destruction of Native American tribes in the 19th century. Through vivid storytelling, it highlights the resilience and tragedy of indigenous peoples, reshaping American history narratives.",
    "isbn": "9780805086843",
    "publisher": "Holt Paperbacks",
    "publishedYear": 1970,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780805086843-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Nepalko Itihas",
    "author": "Gyanmani Nepal",
    "category": "History",
    "description": "This authoritative Nepali book chronicles Nepal’s history from ancient times to the modern era, covering the Licchavi, Malla, and Shah dynasties. A key resource for students, it offers detailed insights into Nepal’s political and cultural evolution.",
    "isbn": "9789937297004",
    "publisher": "Ratna Pustak Bhandar",
    "publishedYear": 2003,
    "coverImage": "https://www.booksmandala.com/images/book/9789937297004.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Nepal: Itihas ra Sanskriti",
    "author": "Satyamohan Joshi",
    "category": "History",
    "description": "Written by a renowned Nepali scholar, this book explores Nepal’s history alongside its cultural heritage, from ancient kingdoms to modern developments. It’s a comprehensive guide to Nepal’s rich historical tapestry.",
    "isbn": "9789937297011",
    "publisher": "Sajha Prakashan",
    "publishedYear": 2007,
    "coverImage": "https://www.booksmandala.com/images/book/9789937297011.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Rana Shasan ko Itihas",
    "author": "Purushottam Shamsher JBR",
    "category": "History",
    "description": "This Nepali book details the history of Nepal’s Rana dynasty, exploring its rise, rule, and fall. With firsthand insights, it’s a key text for understanding Nepal’s autocratic period from 1846 to 1951.",
    "isbn": "9789937297028",
    "publisher": "Ekta Books",
    "publishedYear": 1999,
    "coverImage": "https://www.ektabooks.com/images/book/9789937297028.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Nepalko Rajnitik Itihas",
    "author": "Krishna Hachhethu",
    "category": "History",
    "description": "This Nepali book examines Nepal’s political history, focusing on the transition from monarchy to democracy and the Maoist insurgency. It’s a vital resource for understanding Nepal’s modern political landscape.",
    "isbn": "9789937297035",
    "publisher": "Buddha Publications",
    "publishedYear": 2015,
    "coverImage": "https://www.buddha publications.com/images/book/9789937297035.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Nepalma Samajik Paribartan",
    "author": "Chaitanya Mishra",
    "category": "History",
    "description": "This Nepali book analyzes social changes in Nepal, from caste dynamics to modernization. It explores how historical events shaped Nepal’s society, making it a key text for sociologists and historians.",
    "isbn": "9789937297042",
    "publisher": "Nova Publication",
    "publishedYear": 2012,
    "coverImage": "https://www.novapublication.com.np/images/book/9789937297042.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Himalayan Itihas",
    "author": "Tulsi Ram Vaidya",
    "category": "History",
    "description": "This Nepali book explores the history of the Himalayan region, with a focus on Nepal’s role in trade, culture, and politics. It’s a comprehensive resource for understanding Nepal’s historical significance.",
    "isbn": "9789937297059",
    "publisher": "Heritage Publishers",
    "publishedYear": 2010,
    "coverImage": "https://www.heritagebooks.com.np/images/book/9789937297059.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
//   sci-fi
  {
    "title": "Dune",
    "author": "Frank Herbert",
    "category": "Sci-Fi",
    "description": "Set on the desert planet Arrakis, this epic novel follows Paul Atreides as he navigates political intrigue, ecological challenges, and a galactic power struggle over the valuable spice melange. Herbert’s richly detailed world-building, blending philosophy, religion, and science, makes this a cornerstone of science fiction literature.",
    "isbn": "9780441013593",
    "publisher": "Ace Books",
    "publishedYear": 1965,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780441013593-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Foundation",
    "author": "Isaac Asimov",
    "category": "Sci-Fi",
    "description": "Isaac Asimov’s classic follows mathematician Hari Seldon, who develops psychohistory to predict the fall of a galactic empire. As he establishes the Foundation to preserve knowledge, this novel explores destiny, power, and human resilience across centuries, launching a legendary series.",
    "isbn": "9780553293357",
    "publisher": "Bantam Books",
    "publishedYear": 1951,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780553293357-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Neuromancer",
    "author": "William Gibson",
    "category": "Sci-Fi",
    "description": "This cyberpunk masterpiece follows hacker Case as he navigates a dystopian world of artificial intelligence, cyberspace, and corporate intrigue. Gibson’s visionary novel, which coined the term ‘cyberspace,’ explores technology’s impact on humanity, earning it the Hugo, Nebula, and Philip K. Dick Awards.",
    "isbn": "9780441569595",
    "publisher": "Ace Books",
    "publishedYear": 1984,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780441569595-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "The Left Hand of Darkness",
    "author": "Ursula K. Le Guin",
    "category": "Sci-Fi",
    "description": "Set on the planet Gethen, this novel follows envoy Genly Ai as he navigates a society with fluid gender roles. Le Guin’s profound exploration of culture, identity, and diplomacy, combined with her lyrical prose, makes this a landmark in speculative fiction, winning Hugo and Nebula Awards.",
    "isbn": "9780441478125",
    "publisher": "Ace Books",
    "publishedYear": 1969,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780441478125-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Ender’s Game",
    "author": "Orson Scott Card",
    "category": "Sci-Fi",
    "description": "In a future where Earth faces an alien threat, young Ender Wiggin is trained as a military genius in a brutal space academy. Card’s gripping novel explores leadership, morality, and sacrifice, blending intense strategy with emotional depth, earning it widespread acclaim.",
    "isbn": "9780812550702",
    "publisher": "Tor Books",
    "publishedYear": 1985,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780812550702-M.jpg",
    "availableCopies": 4,
    "totalCopies": 6
  },
  {
    "title": "The Martian",
    "author": "Andy Weir",
    "category": "Sci-Fi",
    "description": "Stranded on Mars after a mission accident, astronaut Mark Watney uses ingenuity and science to survive against impossible odds. Weir’s debut novel combines hard science, humor, and suspense, making it a modern sci-fi classic adapted into a hit film.",
    "isbn": "9780804139021",
    "publisher": "Crown Publishing",
    "publishedYear": 2011,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780804139021-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "Snow Crash",
    "author": "Neal Stephenson",
    "category": "Sci-Fi",
    "description": "In a cyberpunk future, hacker Hiro Protagonist battles a digital virus threatening both virtual and real worlds. Stephenson’s fast-paced novel blends satire, technology, and mythology, pioneering the genre with its vivid depiction of a fragmented, high-tech society.",
    "isbn": "9780553380958",
    "publisher": "Bantam Books",
    "publishedYear": 1992,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780553380958-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Hyperion",
    "author": "Dan Simmons",
    "category": "Sci-Fi",
    "description": "This Hugo Award-winning novel weaves a Canterbury Tales-style narrative of pilgrims on a war-torn universe, seeking answers from the mysterious Shrike. Simmons’ intricate storytelling and philosophical depth make it a sprawling, poetic sci-fi epic.",
    "isbn": "9780553283686",
    "publisher": "Bantam Books",
    "publishedYear": 1989,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780553283686-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "category": "Sci-Fi",
    "description": "Huxley’s dystopian classic depicts a future where genetic engineering, drugs, and conformity suppress individuality. Through characters like Bernard Marx and John the Savage, it explores the cost of technological progress, remaining a chilling critique of societal control.",
    "isbn": "9780060850524",
    "publisher": "Harper Perennial",
    "publishedYear": 1932,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780060850524-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The Time Machine",
    "author": "H.G. Wells",
    "category": "Sci-Fi",
    "description": "H.G. Wells’ pioneering novella follows a Victorian scientist who travels to a distant future, encountering the Eloi and Morlocks. This timeless tale explores time travel, evolution, and class, laying the foundation for modern science fiction.",
    "isbn": "9780141439976",
    "publisher": "Penguin Classics",
    "publishedYear": 1895,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780141439976-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Do Androids Dream of Electric Sheep?",
    "author": "Philip K. Dick",
    "category": "Sci-Fi",
    "description": "In a post-apocalyptic world, bounty hunter Rick Deckard hunts rogue androids indistinguishable from humans. Dick’s novel, the basis for Blade Runner, explores identity, empathy, and technology’s ethical dilemmas in a gritty, philosophical narrative.",
    "isbn": "9780345404473",
    "publisher": "Del Rey",
    "publishedYear": 1968,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780345404473-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Stranger in a Strange Land",
    "author": "Robert A. Heinlein",
    "category": "Sci-Fi",
    "description": "This Hugo Award-winning novel follows Valentine Michael Smith, a human raised on Mars, as he returns to Earth and sparks a cultural revolution. Heinlein’s exploration of religion, freedom, and human nature remains a provocative sci-fi classic.",
    "isbn": "9780441790340",
    "publisher": "Ace Books",
    "publishedYear": 1961,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780441790340-M.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Fahrenheit 451",
    "author": "Ray Bradbury",
    "category": "Sci-Fi",
    "description": "In a dystopian future where books are banned, fireman Guy Montag burns them until he questions his role. Bradbury’s poetic novel warns of censorship, conformity, and the loss of intellectual freedom, remaining a powerful sci-fi allegory.",
    "isbn": "9781451673319",
    "publisher": "Simon & Schuster",
    "publishedYear": 1953,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9781451673319-M.jpg",
    "availableCopies": 3,
    "totalCopies": 5
  },
  {
    "title": "The War of the Worlds",
    "author": "H.G. Wells",
    "category": "Sci-Fi",
    "description": "H.G. Wells’ seminal novel depicts a Martian invasion of Earth, exploring humanity’s vulnerability and resilience. Its vivid portrayal of alien conflict and societal collapse has inspired countless adaptations and remains a sci-fi milestone.",
    "isbn": "9780141441030",
    "publisher": "Penguin Classics",
    "publishedYear": 1898,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780141441030-M.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Flowers for Algernon",
    "author": "Daniel Keyes",
    "category": "Sci-Fi",
    "description": "This moving novel follows Charlie Gordon, a man with intellectual disabilities, as he undergoes an experiment to increase his intelligence. Keyes’ emotional narrative explores ethics, identity, and the human condition, earning it widespread acclaim.",
    "isbn": "9780156030083",
    "publisher": "Harcourt",
    "publishedYear": 1966,
    "coverImage": "https://covers.openlibrary.org/b/isbn/9780156030083-M.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Antaral Yatra",
    "author": "Dhruba Sapkota",
    "category": "Sci-Fi",
    "description": "A pioneering Nepali sci-fi novel, Antaral Yatra imagines a future where Nepali scientists develop interstellar travel. Exploring themes of discovery and cultural identity, it blends Himalayan mysticism with futuristic technology, captivating Nepali readers.",
    "isbn": "9789937297066",
    "publisher": "Book Hill",
    "publishedYear": 2018,
    "coverImage": "https://www.booksmandala.com/images/book/9789937297066.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Bishwo Yuddha 2050",
    "author": "Krishna Abiral",
    "category": "Sci-Fi",
    "description": "This Nepali sci-fi novel envisions a global war in 2050, with Nepal caught in a technological and political conflict. Abiral’s narrative blends speculative warfare with social commentary, making it a popular read among Nepali sci-fi enthusiasts.",
    "isbn": "9789937297073",
    "publisher": "FinePrint",
    "publishedYear": 2015,
    "coverImage": "https://www.booksmandala.com/images/book/9789937297073.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  },
  {
    "title": "Andhakar ko Antim Din",
    "author": "Sanjeev Uprety",
    "category": "Sci-Fi",
    "description": "This Nepali novel explores a dystopian future where a mysterious darkness engulfs Nepal, forcing survivors to rely on ancient knowledge and futuristic technology. Uprety’s blend of speculative fiction and cultural heritage has made it a notable sci-fi work.",
    "isbn": "9789937297080",
    "publisher": "Sajha Prakashan",
    "publishedYear": 2017,
    "coverImage": "https://www.booksmandala.com/images/book/9789937297080.jpg",
    "availableCopies": 2,
    "totalCopies": 3
  },
  {
    "title": "Tara Mandala",
    "author": "Amar Neupane",
    "category": "Sci-Fi",
    "description": "In this Nepali sci-fi novel, a group of explorers discovers a hidden star system tied to ancient Nepali myths. Neupane’s imaginative storytelling weaves cosmic adventure with cultural roots, earning it popularity among young Nepali readers.",
    "isbn": "9789937297097",
    "publisher": "Nepalaya",
    "publishedYear": 2019,
    "coverImage": "https://www.booksmandala.com/images/book/9789937297097.jpg",
    "availableCopies": 2,
    "totalCopies": 4
  },
  {
    "title": "Kalpana ko Sansar",
    "author": "Narayan Dhakal",
    "category": "Sci-Fi",
    "description": "This Nepali sci-fi novel explores a virtual reality world where dreams shape reality, blending futuristic technology with philosophical questions about existence. Dhakal’s engaging narrative has made it a standout in Nepali speculative fiction.",
    "isbn": "9789937297103",
    "publisher": "Ratna Pustak Bhandar",
    "publishedYear": 2016,
    "coverImage": "https://www.booksmandala.com/images/book/9789937297103.jpg",
    "availableCopies": 1,
    "totalCopies": 2
  }

]